services:
  db:
    image: postgres:15-alpine
    container_name: trip_planner_db
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: trip_planner_api
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    container_name: trip_planner_api
    build:
      context: ./backend
      target: development
    ports:
      - "3333:3333"
    environment:
      DATABASE_URL: "postgresql://docker:docker@db:5432/trip_planner_api"
      PORT: 3333
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
      
  #frontend:
   # container_name: trip_planner_frontend
   # build:
    #  context: ./frontend
    #ports:
     # - "3000:3000"
    #volumes:
     # - ./frontend:/app
      #- /app/node_modules
    #depends_on:
     # - api

volumes:
  postgres_data: