services:
  db:
    image: postgres:15-alpine
    container_name: trip_planner_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    container_name: trip_planner_api
    build:
      context: ./backend
      target: development
    ports:
      - "3333:3333"
    environment:
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - PORT=3333
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
      
  #frontend:
   # container_name: trip_planner_frontend
    # build:
    #  context: ./frontend/my-app
    # ports:
    #  - "3000:3000"
    # environment:
    #  - NEXT_PUBLIC_API_URL=http://api:3333
    # volumes:
    #  - ./frontend/my-app:/usr/src/app
    #  - /usr/src/app/node_modules
    # depends_on:
    #  - api

volumes:
  postgres_data: